server:
  port: 8888

spring:
  application:
    name: central-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dishantkamble/central-application-configurations.git
          skip-ssl-validation: true

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
