server:
  port: 8081
spring:
  application:
    name: central-config-server 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dishantkamble/central-application-configurations
          skip-ssl-validation: true
          
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/